### ISSUE TITLE
Cannot Import Name 'selectionload'

### ISSUE THREAD

**Issue by Wolfe1** [pbylicki/rfhub2#108]
Any idea here on why I am receiving this error? Installed from pip.

```
C:\WINDOWS\system32>rfhub2
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\rfhub2.exe\__main__.py", line 4, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\rfhub2\__main__.py", line 7, in <module>
    from rfhub2.main import app
  File "c:\programdata\anaconda3\lib\site-packages\rfhub2\main.py", line 1, in <module>
    from rfhub2.app import create_app
  File "c:\programdata\anaconda3\lib\site-packages\rfhub2\app.py", line 6, in <module>
    from rfhub2.api.router import api_router
  File "c:\programdata\anaconda3\lib\site-packages\rfhub2\api\router.py", line 3, in <module>
    from rfhub2.api.endpoints import collections, healthcheck, keywords, version
  File "c:\programdata\anaconda3\lib\site-packages\rfhub2\api\endpoints\collections.py", line 6, in <module>
    from rfhub2.api.utils.db import get_collection_repository
  File "c:\programdata\anaconda3\lib\site-packages\rfhub2\api\utils\db.py", line 3, in <module>
    from rfhub2.db.repository.keyword_repository import KeywordRepository
  File "c:\programdata\anaconda3\lib\site-packages\rfhub2\db\repository\keyword_repository.py", line 4, in <module>
    from sqlalchemy.orm import selectinload
ImportError: cannot import name 'selectinload'
```

**Comment by MaciejWiczk** [comment]
Hi @Wolfe1, could You tell me what dependencies You are using, by pip freeze? Especially which version of SQLAlchemy? And which python version inside anaconda3?

**Comment by Wolfe1** [comment]
It was indeed my SQLAlchemy version. It was set to 1.1.13 while your requirements.txt is set to 1.3.11. Your setup.py file seems to be allowing any version above 1.1.0 though...

Perhaps you should modify your setup.py to use your requiremnets.txt file to avoid this issue? You would only have to maintain a single file for base requirements that way as well.

```
with open('requirements.txt') as f:
    requirements = f.read().splitlines()
.
.
.
install_requires=requirements,
```

**Comment by MaciejWiczk** [comment]
@Wolfe1 it is to some extent done on purpose. requirements.txt is set to newest awailable versions of each dependency by dependabot, setup.py however is more relaxed, and is set to lowest possible version of each dependency, so it will accept broader number of versions resulting in less conflicts for users. I have a hunch that You had SQLAlchemy set to `1.1.13` while fastapi and others were the newest one, thus breaking.

**Comment by Wolfe1** [comment]
Understandable, just be aware that this issue will probably come up again for anyone moving from the original rfhub (or any other older SQLAlchemy code base) until that setup.py minimum version is increased.

From the error above it seems that keyword_repository.py is importing 'sectionload' that has been added in a version later than 1.1.13. I think this is an incompatibility between the rfhub2 code and the current minimum version in setup.py (1.1.0) rather than another dependency.

**Comment by MaciejWiczk** [comment]
You're totally right. I will create PR for that.
